# Generated by Django 5.0.4 on 2024-06-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(upload_to='image/')),
                ('home_image', models.ImageField(upload_to='image/')),
                ('statistic_estalblished', models.CharField(max_length=200)),
                ('statistic_happy_client', models.CharField(max_length=200)),
                ('statistic_production', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='APP.homepage')),
            ],
        ),
    ]
