# Generated by Django 5.0.4 on 2024-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_raw_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_capcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
    ]
