# Generated by Django 5.0.4 on 2024-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_production_capcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
