# Generated by Django 5.0.4 on 2024-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
