# Generated by Django 5.0.4 on 2024-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
