# Generated by Django 5.0.4 on 2024-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_announcement_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
