# Generated by Django 5.0.4 on 2024-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_announcement_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='phone',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
