# Generated by Django 5.0.4 on 2024-07-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_team_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
