# Generated by Django 4.2.4 on 2024-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
